title: FEASTorg
description: >-
  This is the main FEASTorg landing site, with links to each project.
baseurl: "" # Hosted at https://feastorg.github.io
url: "https://feastorg.github.io"

# Social links
twitter_username: FEASTorg
github_username: FEASTorg
email: contact@feastorg.org

# Theme and plugins
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-titles-from-headings

# Just the Docs settings
logo: /assets/images/cornucopia-feast-banner.png
repository: https://github.com/FEASTorg/FEASTorg.github.io
search: true

# Relative link fixer
relative_links:
  enabled: true
  collections: true

# Pretty URLs
permalink: pretty

# Defaults for imported pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "**/README.md"
    values:
      nav_exclude: true

# Files and directories to exclude from processing
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - _ext/
  - "**/.indexignore"
