title: FEASTorg
description: >-
  This is the main FEASTorg landing site, with links to each project.
baseurl: "" # Hosted at https://feastorg.github.io
url: "https://feastorg.github.io"

# Social links
twitter_username: FEASTorg
github_username: FEASTorg
email: contact@feastorg.org

# Theme and plugins
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs settings
logo: /assets/images/cornucopia-feast-banner.png
repository: https://github.com/FEASTorg/FEASTorg.github.io
search: true
navigation:
  data: navigation

# Exclude directories and files that should not be published
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

# Optional front-matter defaults
defaults:
  - scope:
      path: "" # all files
      type: "posts"
    values:
      layout: "post"
      author: "FEASTorg"
      comments: true
